workflows:
  ios-workflow:
    name: iOS Simulator Build
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build with Swift Package Manager
        script: |
          cd Grounded
          swift build -c release \
            --sdk $(xcrun --sdk iphonesimulator --show-sdk-path) \
            --arch arm64 \
            --arch x86_64
      - name: Create app bundle
        script: |
          cd Grounded
          mkdir -p Grounded.app
          cp -r .build/release/* Grounded.app/ || true
          cp Info.plist Grounded.app/
          cp -r Assets.xcassets Grounded.app/
          cp -r Models Grounded.app/
          cp -r Views Grounded.app/
          cp -r Services Grounded.app/
          cp *.swift Grounded.app/
          zip -r Grounded.zip Grounded.app
    artifacts:
      - Grounded/Grounded.zip
